language: julia
os:
  - osx
julia:
  - 0.4
notifications:
  email: false
env:
  - MPI_IMPL=mpich
before_install:
  - sh ./conf/travis-install-mpi.sh $MPI_IMPL
after_success:
  - if [ "$TRAVIS_JULIA_VERSION" = nightly ]; then julia -e 'cd(Pkg.dir("MPI")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
