language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  - nightly
notifications:
  email: false
env:
  - MPI=mpich
  - MPI=openmpi
before_install:
  - sh ./conf/travis-install-mpi.sh $MPI
before_script:
  - sudo hostname localhost
  - MPIEXEC='mpiexec'
  - test $MPI == mpich2 && MPIEXEC='mpiexec -launcher fork' || true
  - test $MPI == mpich3 && MPIEXEC='mpiexec -launcher fork' || true
